### ISSUE TITLE
HB_Diode.py does not work

### ISSUE THREAD

**Issue by beta68** [victorpreuss/YalRF#1]
Could you please have a look? Error Message is

```
Traceback (most recent call last):
  File "/Users/rudi/Desktop/YalRF/yalrf/HB_Diode.py", line 24, in <module>
    converged, freqs, Vf, time, Vt = hb.run(y)
  File "/Users/rudi/Desktop/YalRF/yalrf/Analyses/HarmonicBalance.py", line 95, in run
    V, vt = self.calc_V0()
  File "/Users/rudi/Desktop/YalRF/yalrf/Analyses/HarmonicBalance.py", line 370, in calc_V0
    ac.run(self.netlist)
  File "/Users/rudi/Desktop/YalRF/yalrf/Analyses/AC.py", line 75, in run
    dev.calc_oppoint(self.xdc, False)
TypeError: Diode.calc_oppoint() takes 2 positional arguments but 3 were given
```

Same error appears for AC_Diode.py

Thank you,
Rudi

**Comment by victorpreuss** [comment]
hey, I'll take a look

**Comment by victorpreuss** [comment]
I've commited some local changes that I had, please see if it worked

**Comment by beta68** [comment]
it’s working perfectly fine. Thank you so much!
